<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>NetworkExtension.kt</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">app</a> &gt; <a href="index.source.html" class="el_package">com.emami.blockfetcher.common.extensions</a> &gt; <span class="el_source">NetworkExtension.kt</span></div><h1>NetworkExtension.kt</h1><pre class="source lang-java linenums">package com.emami.blockfetcher.common.extensions

import com.emami.blockfetcher.common.base.Result
import com.emami.blockfetcher.common.exception.NoConnectivityException
import retrofit2.HttpException
import retrofit2.Response
import timber.log.Timber
import java.io.IOException
import java.net.SocketTimeoutException

internal inline fun &lt;T&gt; invokeApiCall(remoteCall: () -&gt; Response&lt;T&gt;): Result&lt;T&gt; =
<span class="nc" id="L12">    try {</span>
<span class="nc" id="L13">        create(remoteCall())</span>
<span class="nc" id="L14">    } catch (e: Exception) {</span>
        //Timber may log exception into our Crash Analytics Provider (ex. Crashlytics, Flurry, etc)
<span class="nc" id="L16">        Timber.e(e)</span>
<span class="nc" id="L17">        create(e)</span>
<span class="nc" id="L18">    }</span>


//Inspired by GithubBrowserSample project
private fun &lt;T&gt; create(throwable: Throwable): Result&lt;T&gt; {
    //Gracefully wrap known error and return
<span class="pc bpc" id="L24" title="3 of 8 branches missed.">    if (throwable is SocketTimeoutException || throwable is NoConnectivityException || throwable is IOException || throwable is HttpException) {</span>
<span class="pc bpc" id="L25" title="1 of 2 branches missed.">        return Result.Error(throwable.message</span>
<span class="nc" id="L26">            ?: &quot;Unknown error&quot;)</span>
    }
    //Otherwise, For the exceptions such as MalformedJson or else throw the crash upward!
    else {
<span class="fc" id="L30">        Timber.e(&quot;Api Call throwable: $throwable&quot;)</span>
<span class="fc" id="L31">        throw throwable</span>
    }
}

private fun &lt;T&gt; create(response: Response&lt;T&gt;): Result&lt;T&gt; {
<span class="fc" id="L36">    return when {</span>
<span class="fc bfc" id="L37" title="All 2 branches covered.">        response.isSuccessful -&gt; {</span>
<span class="fc" id="L38">            val body = response.body()</span>
            /*
             * Unchecked cast: Any to T -&gt; We are not going to make Result.Success accept nullable types or create Result.Success.Empty or
             * Handle EmptyResponse (code 204) ONLY FOR NOW
             * THIS IS A KNOWN WARNING ISSUE WHICH WE CAN FIX LATER
             */
<span class="fc" id="L44">            Result.Success(</span>
<span class="pc bpc" id="L45" title="1 of 2 branches missed.">                body ?: Any() as T</span>
            )
        }
<span class="pc bpc" id="L48" title="1 of 2 branches missed.">        response.code() == 500 -&gt; Result.Error(</span>
<span class="pc bpc" id="L49" title="1 of 2 branches missed.">            response.message() ?: &quot;Server Unavailable, Try again later.&quot;</span>
        )
        else -&gt; {
<span class="nc" id="L52">            val errorMsg = parseErrorMessage(response)</span>
<span class="nc" id="L53">            Result.Error(</span>
<span class="nc bnc" id="L54" title="All 2 branches missed.">                errorMsg ?: &quot;Unknown Error&quot;,</span>
            )
        }
    }
}

private fun &lt;T&gt; parseErrorMessage(response: Response&lt;T&gt;): String? {
<span class="nc bnc" id="L61" title="All 2 branches missed.">    val msg = response.errorBody()?.string()</span>
<span class="nc bnc" id="L62" title="All 6 branches missed.">    return if (msg.isNullOrEmpty()) {</span>
<span class="nc" id="L63">        response.message()</span>
    } else {
<span class="nc" id="L65">        msg</span>
    }
}

</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.5.201910111838</span></div></body></html>